import 'package:flutter/material.dart';

/// The Cozy Desk - Masa Nesnesi Modeli
class DeskItem {
  final String id;
  final String achievementId;
  final String nameTr;
  final String nameEn;
  final String descriptionTr;
  final String descriptionEn;
  final IconData icon;
  final Color accentColor;
  final double normalizedX; // 0.0 .. 1.0 (Canvas üzerinde X pozisyonu)
  final double normalizedY; // 0.0 .. 1.0 (Canvas üzerinde Y pozisyonu)
  final double size;
  final bool isUnlocked;

  const DeskItem({
    required this.id,
    required this.achievementId,
    required this.nameTr,
    required this.nameEn,
    required this.descriptionTr,
    required this.descriptionEn,
    required this.icon,
    required this.accentColor,
    required this.normalizedX,
    required this.normalizedY,
    this.size = 38.0,
    this.isUnlocked = false,
  });

  String getName(String languageCode) => languageCode == 'en' ? nameEn : nameTr;
  String getDescription(String languageCode) => languageCode == 'en' ? descriptionEn : descriptionTr;

  DeskItem copyWith({bool? isUnlocked}) {
    return DeskItem(
      id: id,
      achievementId: achievementId,
      nameTr: nameTr,
      nameEn: nameEn,
      descriptionTr: descriptionTr,
      descriptionEn: descriptionEn,
      icon: icon,
      accentColor: accentColor,
      normalizedX: normalizedX,
      normalizedY: normalizedY,
      size: size,
      isUnlocked: isUnlocked ?? this.isUnlocked,
    );
  }

  /// Tüm Masa Nesneleri Kataloğu (14 Adet Temel + Özel)
  static List<DeskItem> get defaultItems => [
    const DeskItem(
      id: 'desk_succulent',
      achievementId: 'first_focus',
      nameTr: 'Terracotta Sukulent',
      nameEn: 'Terracotta Succulent',
      descriptionTr: 'Masanın sol köşesinde ilk odaklanmanın canlandırdığı taze bitki.',
      descriptionEn: 'A fresh succulent enlivening the left corner of your desk.',
      icon: Icons.eco_rounded,
      accentColor: Color(0xFF4A7C59),
      normalizedX: 0.12,
      normalizedY: 0.72,
      size: 36.0,
    ),
    const DeskItem(
      id: 'desk_hourglass',
      achievementId: 'focus_1h',
      nameTr: 'Bronz Kum Saati',
      nameEn: 'Bronze Hourglass',
      descriptionTr: 'Zamanın değerini fısıldayan minimalist kum saati.',
      descriptionEn: 'A minimalist hourglass keeping track of focused hours.',
      icon: Icons.hourglass_top_rounded,
      accentColor: Color(0xFFC28E58),
      normalizedX: 0.28,
      normalizedY: 0.58,
      size: 34.0,
    ),
    const DeskItem(
      id: 'desk_matcha_cup',
      achievementId: 'focus_5h',
      nameTr: 'Seramik Sıcak Kupa',
      nameEn: 'Ceramic Warm Mug',
      descriptionTr: 'Ahşap altlığında dinlenen taze matcha kahve kupası.',
      descriptionEn: 'A warm matcha mug resting on a cedar wood saucer.',
      icon: Icons.local_cafe_rounded,
      accentColor: Color(0xFF5B8E6A),
      normalizedX: 0.38,
      normalizedY: 0.70,
      size: 36.0,
    ),
    const DeskItem(
      id: 'desk_candle',
      achievementId: 'focus_25h',
      nameTr: 'Sakinleştirici Soya Mumu',
      nameEn: 'Calm Soy Candle',
      descriptionTr: 'Akşam çalışmalarını sakinleştiren ahşap fitilli aromaterapi mumu.',
      descriptionEn: 'A wooden-wick candle radiating calm across your workspace.',
      icon: Icons.wb_incandescent_rounded,
      accentColor: Color(0xFFE5A93C),
      normalizedX: 0.20,
      normalizedY: 0.42,
      size: 34.0,
    ),
    const DeskItem(
      id: 'desk_lamp',
      achievementId: 'focus_50h',
      nameTr: 'Yeşil Mimari Lamba',
      nameEn: 'Banker Desk Lamp',
      descriptionTr: 'Masanın sağ köşesini sıcak tonlarla aydınlatan eklemli lamba.',
      descriptionEn: 'An articulated banker lamp casting warm light on your notebook.',
      icon: Icons.lightbulb_rounded,
      accentColor: Color(0xFF2E6342),
      normalizedX: 0.84,
      normalizedY: 0.30,
      size: 44.0,
    ),
    const DeskItem(
      id: 'desk_moon_lamp',
      achievementId: 'focus_100h',
      nameTr: 'Mat Seramik Hilal',
      nameEn: 'Ceramic Crescent Moon',
      descriptionTr: '100 saatlik ustalığın simgesi; masanın üstünde parıldayan ay.',
      descriptionEn: 'The emblem of 100 focused hours, glowing softly.',
      icon: Icons.nightlight_round,
      accentColor: Color(0xFFE0C475),
      normalizedX: 0.74,
      normalizedY: 0.18,
      size: 40.0,
    ),
    const DeskItem(
      id: 'desk_potted_plant',
      achievementId: 'routine_3d',
      nameTr: 'Beton Saksı Çiçeği',
      nameEn: 'Concrete Potted Plant',
      descriptionTr: 'Masanın arkasında kök salan ve serpilip büyüyen taze fidan.',
      descriptionEn: 'A healthy sprout taking deep root on your desk.',
      icon: Icons.grass_rounded,
      accentColor: Color(0xFF3F7753),
      normalizedX: 0.08,
      normalizedY: 0.35,
      size: 38.0,
    ),
    const DeskItem(
      id: 'desk_stationery_set',
      achievementId: 'routine_7d',
      nameTr: 'Teknik Çizim & Cetvel',
      nameEn: 'Brass Ruler & Pen',
      descriptionTr: 'Düzen ve ritmi temsil eden pirinç cetvel ve çizim kalemi.',
      descriptionEn: 'Precision stationery representing consistent weekly discipline.',
      icon: Icons.architecture_rounded,
      accentColor: Color(0xFF8C7355),
      normalizedX: 0.44,
      normalizedY: 0.62,
      size: 32.0,
    ),
    const DeskItem(
      id: 'desk_tea_set',
      achievementId: 'routine_30d',
      nameTr: 'Zen Çay Seremonisi',
      nameEn: 'Zen Tea Ceremony Set',
      descriptionTr: 'Bambu çırpıcı ve seramik matcha kasesiyle dinginlik köşesi.',
      descriptionEn: 'Traditional bamboo chasen and chawan tea ceremony set.',
      icon: Icons.spa_rounded,
      accentColor: Color(0xFF437554),
      normalizedX: 0.88,
      normalizedY: 0.68,
      size: 40.0,
    ),
    const DeskItem(
      id: 'desk_notepad',
      achievementId: 'plan_10',
      nameTr: 'Minimal Not Klipsi',
      nameEn: 'Minimal Clipboard',
      descriptionTr: 'Günlük önceliklerin sıralandığı metal klipsli pano.',
      descriptionEn: 'A sleek clipboard holding today\'s essential priorities.',
      icon: Icons.checklist_rounded,
      accentColor: Color(0xFF4A6856),
      normalizedX: 0.56,
      normalizedY: 0.72,
      size: 34.0,
    ),
    const DeskItem(
      id: 'desk_book_stack',
      achievementId: 'plan_50',
      nameTr: 'Keten Ciltli Defterler',
      nameEn: 'Linen Notebook Stack',
      descriptionTr: 'Çalışmaların biriktiği 3 adet nötr kumaş ciltli defter.',
      descriptionEn: 'A neat stack of three clothbound archive journals.',
      icon: Icons.collections_bookmark_rounded,
      accentColor: Color(0xFF637D94),
      normalizedX: 0.68,
      normalizedY: 0.54,
      size: 38.0,
    ),
    const DeskItem(
      id: 'desk_journal',
      achievementId: 'plan_100',
      nameTr: 'Deri Seyahat Ajandası',
      nameEn: 'Traveler\'s Leather Journal',
      descriptionTr: 'Pirinç klipsli, kalın eskitme deri ciltli başyapıt ajandası.',
      descriptionEn: 'An heirloom leather planner with a solid brass fastener.',
      icon: Icons.book_rounded,
      accentColor: Color(0xFF8A5A36),
      normalizedX: 0.52,
      normalizedY: 0.46,
      size: 42.0,
    ),
    const DeskItem(
      id: 'desk_wall_calendar',
      achievementId: 'first_week',
      nameTr: 'Ahşap Masa Takvimi',
      nameEn: 'Wooden Block Calendar',
      descriptionTr: 'Arka duvara dayalı, günleri zarifçe sayan minimalist takvim.',
      descriptionEn: 'A wooden base tear-off calendar on the background shelf.',
      icon: Icons.calendar_today_rounded,
      accentColor: Color(0xFF6D8274),
      normalizedX: 0.24,
      normalizedY: 0.16,
      size: 34.0,
    ),
    const DeskItem(
      id: 'desk_photo_frame',
      achievementId: 'first_month',
      nameTr: 'Masa Çerçevesi',
      nameEn: 'Mini Portrait Frame',
      descriptionTr: 'Kullanıcının avatar karakterini sergileyen mat pirinç çerçeve.',
      descriptionEn: 'A miniature portrait frame showing your Calenda companion.',
      icon: Icons.portrait_rounded,
      accentColor: Color(0xFF9E814D),
      normalizedX: 0.48,
      normalizedY: 0.14,
      size: 36.0,
    ),
    const DeskItem(
      id: 'desk_trophy',
      achievementId: 'club_session',
      nameTr: 'Geometrik Altın Kupa',
      nameEn: 'Geometric Trophy',
      descriptionTr: 'Kulüp seansında birlikte kazanılan minimalist zafer kupası.',
      descriptionEn: 'A sleek geometric study trophy won with your club comrades.',
      icon: Icons.military_tech_rounded,
      accentColor: Color(0xFFD4AF37),
      normalizedX: 0.74,
      normalizedY: 0.68,
      size: 38.0,
    ),
    const DeskItem(
      id: 'desk_star_globe',
      achievementId: 'night_owl',
      nameTr: 'Dönen Gece Saati',
      nameEn: 'Rotating Night Sphere',
      descriptionTr: 'Gece çalışanların masasını süsleyen ince metalik küre.',
      descriptionEn: 'A subtle metallic sphere keeping watch over night sessions.',
      icon: Icons.public_rounded,
      accentColor: Color(0xFF5D737E),
      normalizedX: 0.88,
      normalizedY: 0.48,
      size: 36.0,
    ),
  ];
}
